baseURL = "https://javadsajjadi.ir"
languageCode = "fa"
title = "جوادسجادی"
defaultContentLanguage = "fa"
enableRobotsTXT = true
summaryLength = "30"


 paginate = 3

[params]
  description = "فارغ‌التحصیل حقوق، عضو کانون نویسندگان ایران"
  author = "سیدجواد سجادی"
  faviconfile            = "img/leaf.ico"
[permalinks]
crime  = "book/:filename"

[menu]
  [[menu.main]]
    name = "خانه"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "کتاب‌"
     identifier = "books"
    url = "/books/"
    weight = 2
  [[menu.main]]
    name = "فیلم‌"
    identifier = "movies"
    url = "/movies/"
    weight = 3
  [[menu.main]]
    name = "قانون"
    identifier = "i-pen"
    url = "/music/"
    weight = "6"
   [[menu.main]]
    name = "قلم‌من"
    identifier = "pen"
    url = "https://i-pen.ir"
    weight = 4
   


 [taxonomies]
  category = "categories"
  tag = "tags"

 [related]
  threshold = 80
  includeNewer = true
  toLower = true
  indices = [
    { name = "categories", weight = 50 }
  ]

  [outputs]
    home = ["HTML", "RSS", "JSON"]
    page = ["html", "json"]
